Document need for Python 3.6
I ran into:

```python
    print(f"Sampling every {sample_period:,} CPU cycles")
                                                       ^
SyntaxError: invalid syntax
```

on an older Python due to the use of [f-strings](https://www.python.org/dev/peps/pep-0498/).